sudo: false
language: perl
before_install:
  - >-
    curl -X POST -H "Content-Type: application/json" -H "Authorization: token
    $GH_TOKEN" -d "{\"state\":\"pending\",\"description\":\"Dependent build
    created\",\"context\":\"continuous-integration/travis-ci/perl-hooks-handler\",\"target_url\":\"https://travis-ci.org/apiaryio/dredd/builds/$TRAVIS_BUILD_ID\"}"
    'https://api.github.com/repos/apiaryio/dredd/statuses/38edf15f849dc7ea7a1ce68a9341971fe5efb844'
  - npm install -g npm@latest
  - npm link --python=python2 ./__dredd__
  - bundle install
script:
  - perl Build.PL && ./Build build && ./Build test
  - ./Build install
  - bundle exec cucumber
perl: '5.22'
env:
  global:
    secure: >-
      bXqGSB7LSQAt5wsNNkmhtQWaEUMKzLTvfuslG3A4vgTYN4K8Ic2dXdUtUJjxpFbItO8x+oOrKxSXTjohz4tj2g0Qao2cc3JluMJ9s8yc8J/TDo1qTWoACrpZbfy8KuQxtekv8gPZsqUFbDxS38mS/NCdUYe2Sa4jWDWMFyPXRrw=
after_failure:
  - >-
    curl -X POST -H "Content-Type: application/json" -H "Authorization: token
    $GH_TOKEN" -d "{\"state\":\"error\",\"description\":\"Dependent build
    finished\",\"context\":\"continuous-integration/travis-ci/perl-hooks-handler\",\"target_url\":\"https://travis-ci.org/apiaryio/dredd/builds/$TRAVIS_BUILD_ID\"}"
    'https://api.github.com/repos/apiaryio/dredd/statuses/38edf15f849dc7ea7a1ce68a9341971fe5efb844'
after_success:
  - >-
    curl -X POST -H "Content-Type: application/json" -H "Authorization: token
    $GH_TOKEN" -d "{\"state\":\"success\",\"description\":\"Dependent build
    finished\",\"context\":\"continuous-integration/travis-ci/perl-hooks-handler\",\"target_url\":\"https://travis-ci.org/apiaryio/dredd/builds/$TRAVIS_BUILD_ID\"}"
    'https://api.github.com/repos/apiaryio/dredd/statuses/38edf15f849dc7ea7a1ce68a9341971fe5efb844'
  - >-
    if [[ $TRAVIS_BRANCH = master ]]; then echo "Deleting aborted (master)" &&
    exit 1; fi
  - git branch -D $TRAVIS_BRANCH
  - >-
    git remote set-url origin "https://$GH_TOKEN@github.com/apiaryio/dredd.git"
    > /dev/null 2>&1
  - git push origin -f --delete $TRAVIS_BRANCH > /dev/null 2>&1
