sudo: false
language: python
before_install:
  - >-
    curl -X POST -H "Content-Type: application/json" -H "Authorization: token
    $GH_TOKEN" -d "{\"state\":\"pending\",\"description\":\"Dependent build
    created\",\"context\":\"continuous-integration/travis-ci/python-hooks-handler\",\"target_url\":\"https://travis-ci.org/apiaryio/dredd/builds/$TRAVIS_BUILD_ID\"}"
    'https://api.github.com/repos/apiaryio/dredd/statuses/38edf15f849dc7ea7a1ce68a9341971fe5efb844'
  - npm install -g npm@latest
  - node --version
  - npm link --python=python2 ./__dredd__
  - bundle install
python: '3.5'
script:
  - python -B -m unittest discover
  - pip install -e .
  - bundle exec cucumber
env:
  global:
    secure: >-
      I5fsJ/vsp/IA+016GtlP7FcOazlm7ZJRbAHeAXUS6Nhob1LHvDpTPQ45jEPykaO8c9RHluCSe1ziOYNnixJeittL5qVFv4oXWh73t8hKOkLtVQxLrfludF8a6rLMvKmPe/Kzu4B1Zim1uaDwVZT8fUObg4XxyqIp+B81wM0NbvM=
after_failure:
  - >-
    curl -X POST -H "Content-Type: application/json" -H "Authorization: token
    $GH_TOKEN" -d "{\"state\":\"error\",\"description\":\"Dependent build
    finished\",\"context\":\"continuous-integration/travis-ci/python-hooks-handler\",\"target_url\":\"https://travis-ci.org/apiaryio/dredd/builds/$TRAVIS_BUILD_ID\"}"
    'https://api.github.com/repos/apiaryio/dredd/statuses/38edf15f849dc7ea7a1ce68a9341971fe5efb844'
after_success:
  - >-
    curl -X POST -H "Content-Type: application/json" -H "Authorization: token
    $GH_TOKEN" -d "{\"state\":\"success\",\"description\":\"Dependent build
    finished\",\"context\":\"continuous-integration/travis-ci/python-hooks-handler\",\"target_url\":\"https://travis-ci.org/apiaryio/dredd/builds/$TRAVIS_BUILD_ID\"}"
    'https://api.github.com/repos/apiaryio/dredd/statuses/38edf15f849dc7ea7a1ce68a9341971fe5efb844'
  - >-
    if [[ $TRAVIS_BRANCH = master ]]; then echo "Deleting aborted (master)" &&
    exit 1; fi
  - git branch -D $TRAVIS_BRANCH
  - >-
    git remote set-url origin "https://$GH_TOKEN@github.com/apiaryio/dredd.git"
    > /dev/null 2>&1
  - git push origin -f --delete $TRAVIS_BRANCH > /dev/null 2>&1
